name: test

on:
  push:
    paths:
      - "**.js"
      - "**.jsx"
      - "package.json"
    branches:
      - main
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "package.json"
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install --audit=false --fund=false --package-lock=false
          npm test
